# Change these first
owner: diegoaces # Your GitHub organization or username, where this repository lives
repo: orangepet_status # The name of this repository

sites:
  - name: Orangepet
    url: https://www.orangepet.cl

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  #logoUrl: https://orangepet.cl/media/wysiwyg/codazon/grocery_gourmet/home/Orangepet-350-60.png
  name: Orangepet
  introTitle: ""
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
